version: '2'

volumes:
  orderer.jet-network.com:
  peer0.100mb.jet-network.com:
  peer1.100mb.jet-network.com:
  peer0.thinkright.jet-network.com:
  peer1.thinkright.jet-network.com:

networks:
  byfn:

services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-100mb
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.100mb.jet-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e95caf6fe75e88ffcabab71d43fde78f594cd7a801d91f3676c6a0952b58820d_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.100mb.jet-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e95caf6fe75e88ffcabab71d43fde78f594cd7a801d91f3676c6a0952b58820d_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/100mb.jet-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_100MB
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-thinkright
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.thinkright.jet-network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/07247530785f658f8311394b5a4d0d6c4138e5c15631f2c3c94c7c5f0e444a44_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.thinkright.jet-network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/07247530785f658f8311394b5a4d0d6c4138e5c15631f2c3c94c7c5f0e444a44_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/thinkright.jet-network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_ThinkRight
    networks:
      - byfn

  orderer.jet-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.jet-network.com
    container_name: orderer.jet-network.com
    networks:
      - byfn

  peer0.100mb.jet-network.com:
    container_name: peer0.100mb.jet-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.100mb.jet-network.com
    networks:
      - byfn

  peer1.100mb.jet-network.com:
    container_name: peer1.100mb.jet-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.100mb.jet-network.com
    networks:
      - byfn

  peer0.thinkright.jet-network.com:
    container_name: peer0.thinkright.jet-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.thinkright.jet-network.com
    networks:
      - byfn

  peer1.thinkright.jet-network.com:
    container_name: peer1.thinkright.jet-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.thinkright.jet-network.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.100mb.jet-network.com:7051
      - CORE_PEER_LOCALMSPID=100MBMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/100mb.jet-network.com/peers/peer0.100mb.jet-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/100mb.jet-network.com/peers/peer0.100mb.jet-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/100mb.jet-network.com/peers/peer0.100mb.jet-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/100mb.jet-network.com/users/Admin@100mb.jet-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./../chaincode/:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.jet-network.com
      - peer0.100mb.jet-network.com
      - peer1.100mb.jet-network.com
      - peer0.thinkright.jet-network.com
      - peer1.thinkright.jet-network.com
    networks:
      - byfn